version: '2.2'
services:
  sentinel:
    build:
      context: .
      args:
        SENTINEL_VERSION: ${SENTINEL_VERSION}
    image: sentinel:compose-latest
  sentinel-test:
    image: sentinel:compose-latest
    working_dir: /test
    command: ["test"]
    volumes:
      - ./test:/test:ro

